# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
industries = ["Advertising", "Aerospace", "Arts", "Chemicals/Rubber/Plastics", "Consulting", "Consulting: Financial Advisory Services", "Consulting: General Management", "Consulting: Healthcare", "Consulting: Information Technology", "Consulting: Logistics", "Consulting: Strategy", "Consulting: Products", "Education", "Energy/Utilities", "Entertainment/Leisure/Sports", "Environmental/Agriculture", "Executive Search", "Fin Serv: Accounting/Audit/Tax", "Fin Serv: Commercial Banking", "Fin Serv: Diversified Financial Services", "Fin Serv: Insurance", "Fin Serv: Investment Banking & Brokerage", "Fin Serv: Investment/Portfolio Management", "Fin Serv: Merchant Banking", "Fin Serv: Mergers & Acquisitions", "Fin Serv: Private Equity/ Venture Capital", "Financial Services", "Food Services/Lodging", "Government", "Green Business", "Healthcare/Biotechnology/Pharmaceuticals", "Industrial Equipment/Machinery", "Legal Services", "Marketing/Media/Communications", "Military", "Not-For-Profit", "Other", "Paper/Forest Products", "Printing/Publishing", "Real Estate/Construction/Engineering", "Retail/Wholesale", "Technology", "Technology Communications & Information Systems", "Technology Computers/Hardware", "Technology E-Commerce/Internet", "Technology Electronics", "Technology Semiconductors", "Technology Software", "Telecommunications", "Transportation & Equipment", "Widely Diversified Manufacturing", "Widely Diversified Services"]

  Industry.destroy_all
  industries.each do |industry|
    i = Industry.new
    i.name = industry
    i.save
  end
  puts "There are now #{Industry.count} industries registered"

# Seed functions
functions = ["Accounting/Control", "Administration", "Advertising", "Asset Management", "Brand/Product Management", "Business Development", "Business Development/Strategy/Research", "Consulting", "Corporate Finance", "Development", "Economic Analysis", "Entrepreneur/Owner", "Entrepreneur/Small Business", "Fin. – Accounting/Control", "Fin. – Banking", "Fin. – Commercial Banking", "Fin. – Corporate Finance/Underwriting", "Fin. – Financial Advisory", "Fin. – Investment Banking/Brokerage", "Fin. – Investment Portfolio Management", "Fin. – Management", "Fin. – Mergers and Acquisitions", "Fin. – Private Client Services", "Fin. – Public Finance", "Fin.- Research (Equity/Fixed Inc.)", "Fin. – Sales & Trading", "Fin.- Treasury, Analyst", "Fin.- Venture Capital/Private Equity", "General Management", "Healthcare", "Human Resources", "Information Systems", "Information Technology", "International Development", "Investor Relations/PR/Communications", "Law/Legal", "Lending/Relationship Management", "Management Consulting", "Market Research", "Marketing – Advertising", "Marketing – Brand/Product Management", "Marketing – Research", "Marketing – Sales", "Mergers and Acquisitions", "Operations/Logistics", "Operations/Production", "Other", "Private Client Services", "Property Management", "Public Finance", "Public Relations", "Real Estate", "Research & Development Management", "Research (Buy Side)", "Research (Sell Side)", "Sales", "Sales and Trading", "Strategic Planning (Internal)", "Treasury Analysis", "Venture Capital/Private Equity"]

  Function.destroy_all
  functions.each do |function|
    fn = Function.new
    fn.name = function
    fn.save
  end
  puts "There are now #{Function.count} functions registered"

# Seed interests
interests = [{"name" => "Africa Business Club", "type_club" => "Affinity"},
{"name" => "Asian Management Association", "type_club" => "Affinity"},
{"name" => "Australia/New Zealand/Oceania Management Association", "type_club" => "Affinity"},
{"name" => "Black Management Association", "type_club" => "Affinity"},
{"name" => "California Business Club", "type_club" => "Affinity"},
{"name" => "Canada Club", "type_club" => "Affinity"},
{"name" => "Catholics At Kellogg", "type_club" => "Affinity"},
{"name" => "Chinese Business Club", "type_club" => "Affinity"},
{"name" => "Christian Fellowship", "type_club" => "Affinity"},
{"name" => "European Business Club", "type_club" => "Affinity"},
{"name" => "Family Enterprise Club", "type_club" => "Affinity"},
{"name" => "Gay And Lesbian Management Association", "type_club" => "Affinity"},
{"name" => "India Business Club", "type_club" => "Affinity"},
{"name" => "Japan Club", "type_club" => "Affinity"},
{"name" => "Jewish Business Association", "type_club" => "Affinity"},
{"name" => "Kellogg Veterans Association", "type_club" => "Affinity"},
{"name" => "Latin American Hispanic And Iberian Management Association", "type_club" => "Affinity"},
{"name" => "Latter-Day Saints Student Association", "type_club" => "Affinity"},
{"name" => "Middle East And North Africa Club", "type_club" => "Affinity"},
{"name" => "Muslim Cultural Business Association", "type_club" => "Affinity"},
{"name" => "Southeast Asia Club", "type_club" => "Affinity"},
{"name" => "Women'S Business Association", "type_club" => "Affinity"},
{"name" => "Automotive Club", "type_club" => "Professional"},
{"name" => "Big Data And Analytics Club", "type_club" => "Professional"},
{"name" => "Business Leadership Club", "type_club" => "Professional"},
{"name" => "Corporate Finance Club", "type_club" => "Professional"},
{"name" => "Distressed Management Club", "type_club" => "Professional"},
{"name" => "Education Industry Club", "type_club" => "Professional"},
{"name" => "Emerging Markets Club", "type_club" => "Professional"},
{"name" => "Energy Club", "type_club" => "Professional"},
{"name" => "Entrepeneurship Club", "type_club" => "Professional"},
{"name" => "Food And Agribusiness Club", "type_club" => "Professional"},
{"name" => "General Management Club", "type_club" => "Professional"},
{"name" => "High Tech Club", "type_club" => "Professional"},
{"name" => "Hospitaltity Club", "type_club" => "Professional"},
{"name" => "Hub", "type_club" => "Professional"},
{"name" => "Innovation And Design Association", "type_club" => "Professional"},
{"name" => "Investment Banking And Capital Markets", "type_club" => "Professional"},
{"name" => "Investment Management Club", "type_club" => "Professional"},
{"name" => "Media And Entertainment Club", "type_club" => "Professional"},
{"name" => "Net Impact", "type_club" => "Professional"},
{"name" => "Operations Management Club", "type_club" => "Professional"},
{"name" => "Private Equity And Venture Capital Club", "type_club" => "Professional"},
{"name" => "Real Estate Club", "type_club" => "Professional"},
{"name" => "Retail And Luxury Goods Club", "type_club" => "Professional"},
{"name" => "Sports Business Club", "type_club" => "Professional"},
{"name" => "Strategy And Business Development Club", "type_club" => "Professional"},
{"name" => "Transportation Club", "type_club" => "Professional"}]

  Interest.destroy_all
  interests.each do |interest|
    int = Interest.new
    int.name = interest["name"]
    int.type_club = interest["type_club"]
    int.save
  end
  puts "There are now #{Interest.count} interests registered"

# Seed programs
programs = ["1Y", "2Y", "JD-MBA", "MD-MBA", "MMM"]

  Program.destroy_all
  programs.each do |program|
    p = Program.new
    p.name = program
    p.save
  end
  puts "There are now #{Program.count} programs registered"

# Seed countries
countries = [{"id" => "AF", "name" => "Afghanistan"},
{"id" => "AL", "name" => "Albania"},
{"id" => "DZ", "name" => "Algeria"},
{"id" => "AS", "name" => "American Samoa"},
{"id" => "AD", "name" => "Andorra"},
{"id" => "AO", "name" => "Angola"},
{"id" => "AI", "name" => "Anguilla"},
{"id" => "AQ", "name" => "Antarctica"},
{"id" => "AG", "name" => "Antigua and Barbuda"},
{"id" => "AR", "name" => "Argentina"},
{"id" => "AM", "name" => "Armenia"},
{"id" => "AW", "name" => "Aruba"},
{"id" => "AU", "name" => "Australia"},
{"id" => "AT", "name" => "Austria"},
{"id" => "AZ", "name" => "Azerbaijan"},
{"id" => "BS", "name" => "Bahamas"},
{"id" => "BH", "name" => "Bahrain"},
{"id" => "BD", "name" => "Bangladesh"},
{"id" => "BB", "name" => "Barbados"},
{"id" => "BY", "name" => "Belarus"},
{"id" => "BE", "name" => "Belgium"},
{"id" => "BZ", "name" => "Belize"},
{"id" => "BJ", "name" => "Benin"},
{"id" => "BM", "name" => "Bermuda"},
{"id" => "BT", "name" => "Bhutan"},
{"id" => "BO", "name" => "Bolivia, Plurinational State of"},
{"id" => "BQ", "name" => "Bonaire, Sint Eustatius and Saba"},
{"id" => "BA", "name" => "Bosnia and Herzegovina"},
{"id" => "BW", "name" => "Botswana"},
{"id" => "BV", "name" => "Bouvet Island"},
{"id" => "BR", "name" => "Brazil"},
{"id" => "IO", "name" => "British Indian Ocean Territory"},
{"id" => "BN", "name" => "Brunei Darussalam"},
{"id" => "BG", "name" => "Bulgaria"},
{"id" => "BF", "name" => "Burkina Faso"},
{"id" => "BI", "name" => "Burundi"},
{"id" => "KH", "name" => "Cambodia"},
{"id" => "CM", "name" => "Cameroon"},
{"id" => "CA", "name" => "Canada"},
{"id" => "CV", "name" => "Cape Verde"},
{"id" => "KY", "name" => "Cayman Islands"},
{"id" => "CF", "name" => "Central African Republic"},
{"id" => "TD", "name" => "Chad"},
{"id" => "CL", "name" => "Chile"},
{"id" => "CN", "name" => "China"},
{"id" => "CX", "name" => "Christmas Island"},
{"id" => "CC", "name" => "Cocos (Keeling) Islands"},
{"id" => "CO", "name" => "Colombia"},
{"id" => "KM", "name" => "Comoros"},
{"id" => "CG", "name" => "Congo"},
{"id" => "CD", "name" => "Congo, The Democratic Republic of the"},
{"id" => "CK", "name" => "Cook Islands"},
{"id" => "CR", "name" => "Costa Rica"},
{"id" => "HR", "name" => "Croatia"},
{"id" => "CU", "name" => "Cuba"},
{"id" => "CW", "name" => "Cura&ccedil;ao"},
{"id" => "CY", "name" => "Cyprus"},
{"id" => "CZ", "name" => "Czech Republic"},
{"id" => "CI", "name" => "C&ocirc;te d&#39;Ivoire"},
{"id" => "DK", "name" => "Denmark"},
{"id" => "DJ", "name" => "Djibouti"},
{"id" => "DM", "name" => "Dominica"},
{"id" => "DO", "name" => "Dominican Republic"},
{"id" => "EC", "name" => "Ecuador"},
{"id" => "EG", "name" => "Egypt"},
{"id" => "SV", "name" => "El Salvador"},
{"id" => "GQ", "name" => "Equatorial Guinea"},
{"id" => "ER", "name" => "Eritrea"},
{"id" => "EE", "name" => "Estonia"},
{"id" => "ET", "name" => "Ethiopia"},
{"id" => "FK", "name" => "Falkland Islands (Malvinas)"},
{"id" => "FO", "name" => "Faroe Islands"},
{"id" => "FJ", "name" => "Fiji"},
{"id" => "FI", "name" => "Finland"},
{"id" => "FR", "name" => "France"},
{"id" => "GF", "name" => "French Guiana"},
{"id" => "PF", "name" => "French Polynesia"},
{"id" => "TF", "name" => "French Southern Territories"},
{"id" => "GA", "name" => "Gabon"},
{"id" => "GM", "name" => "Gambia"},
{"id" => "GE", "name" => "Georgia"},
{"id" => "DE", "name" => "Germany"},
{"id" => "GH", "name" => "Ghana"},
{"id" => "GI", "name" => "Gibraltar"},
{"id" => "GR", "name" => "Greece"},
{"id" => "GL", "name" => "Greenland"},
{"id" => "GD", "name" => "Grenada"},
{"id" => "GP", "name" => "Guadeloupe"},
{"id" => "GU", "name" => "Guam"},
{"id" => "GT", "name" => "Guatemala"},
{"id" => "GG", "name" => "Guernsey"},
{"id" => "GN", "name" => "Guinea"},
{"id" => "GW", "name" => "Guinea-Bissau"},
{"id" => "GY", "name" => "Guyana"},
{"id" => "HT", "name" => "Haiti"},
{"id" => "HM", "name" => "Heard Island and McDonald Islands"},
{"id" => "VA", "name" => "Holy See (Vatican City State)"},
{"id" => "HN", "name" => "Honduras"},
{"id" => "HK", "name" => "Hong Kong"},
{"id" => "HU", "name" => "Hungary"},
{"id" => "IS", "name" => "Iceland"},
{"id" => "IN", "name" => "India"},
{"id" => "id", "name" => "Indonesia"},
{"id" => "IR", "name" => "Iran, Islamic Republic of"},
{"id" => "IQ", "name" => "Iraq"},
{"id" => "IE", "name" => "Ireland"},
{"id" => "IM", "name" => "Isle of Man"},
{"id" => "IL", "name" => "Israel"},
{"id" => "IT", "name" => "Italy"},
{"id" => "JM", "name" => "Jamaica"},
{"id" => "JP", "name" => "Japan"},
{"id" => "JE", "name" => "Jersey"},
{"id" => "JO", "name" => "Jordan"},
{"id" => "KZ", "name" => "Kazakhstan"},
{"id" => "KE", "name" => "Kenya"},
{"id" => "KI", "name" => "Kiribati"},
{"id" => "KP", "name" => "Korea, Democratic People&#39;s Republic of"},
{"id" => "KR", "name" => "Korea, Republic of"},
{"id" => "KW", "name" => "Kuwait"},
{"id" => "KG", "name" => "Kyrgyzstan"},
{"id" => "LA", "name" => "Lao People&#39;s Democratic Republic"},
{"id" => "LV", "name" => "Latvia"},
{"id" => "LB", "name" => "Lebanon"},
{"id" => "LS", "name" => "Lesotho"},
{"id" => "LR", "name" => "Liberia"},
{"id" => "LY", "name" => "Libya"},
{"id" => "LI", "name" => "Liechtenstein"},
{"id" => "LT", "name" => "Lithuania"},
{"id" => "LU", "name" => "Luxembourg"},
{"id" => "MO", "name" => "Macao"},
{"id" => "MK", "name" => "Macedonia, Republic of"},
{"id" => "MG", "name" => "Madagascar"},
{"id" => "MW", "name" => "Malawi"},
{"id" => "MY", "name" => "Malaysia"},
{"id" => "MV", "name" => "Maldives"},
{"id" => "ML", "name" => "Mali"},
{"id" => "MT", "name" => "Malta"},
{"id" => "MH", "name" => "Marshall Islands"},
{"id" => "MQ", "name" => "Martinique"},
{"id" => "MR", "name" => "Mauritania"},
{"id" => "MU", "name" => "Mauritius"},
{"id" => "YT", "name" => "Mayotte"},
{"id" => "MX", "name" => "Mexico"},
{"id" => "FM", "name" => "Micronesia, Federated States of"},
{"id" => "MD", "name" => "Moldova, Republic of"},
{"id" => "MC", "name" => "Monaco"},
{"id" => "MN", "name" => "Mongolia"},
{"id" => "ME", "name" => "Montenegro"},
{"id" => "MS", "name" => "Montserrat"},
{"id" => "MA", "name" => "Morocco"},
{"id" => "MZ", "name" => "Mozambique"},
{"id" => "MM", "name" => "Myanmar"},
{"id" => "NA", "name" => "Namibia"},
{"id" => "NR", "name" => "Nauru"},
{"id" => "NP", "name" => "Nepal"},
{"id" => "NL", "name" => "Netherlands"},
{"id" => "NC", "name" => "New Caledonia"},
{"id" => "NZ", "name" => "New Zealand"},
{"id" => "NI", "name" => "Nicaragua"},
{"id" => "NE", "name" => "Niger"},
{"id" => "NG", "name" => "Nigeria"},
{"id" => "NU", "name" => "Niue"},
{"id" => "NF", "name" => "Norfolk Island"},
{"id" => "MP", "name" => "Northern Mariana Islands"},
{"id" => "NO", "name" => "Norway"},
{"id" => "OM", "name" => "Oman"},
{"id" => "PK", "name" => "Pakistan"},
{"id" => "PW", "name" => "Palau"},
{"id" => "PS", "name" => "Palestinian Territory, Occupied"},
{"id" => "PA", "name" => "Panama"},
{"id" => "PG", "name" => "Papua New Guinea"},
{"id" => "PY", "name" => "Paraguay"},
{"id" => "PE", "name" => "Peru"},
{"id" => "PH", "name" => "Philippines"},
{"id" => "PN", "name" => "Pitcairn"},
{"id" => "PL", "name" => "Poland"},
{"id" => "PT", "name" => "Portugal"},
{"id" => "QA", "name" => "Qatar"},
{"id" => "RO", "name" => "Romania"},
{"id" => "RU", "name" => "Russian Federation"},
{"id" => "RW", "name" => "Rwanda"},
{"id" => "RE", "name" => "R&eacute;union"},
{"id" => "BL", "name" => "Saint Barth&eacute;lemy"},
{"id" => "SH", "name" => "Saint Helena, Ascension and Tristan da Cunha"},
{"id" => "KN", "name" => "Saint Kitts and Nevis"},
{"id" => "LC", "name" => "Saint Lucia"},
{"id" => "MF", "name" => "Saint Martin (French part)"},
{"id" => "PM", "name" => "Saint Pierre and Miquelon"},
{"id" => "VC", "name" => "Saint Vincent and the Grenadines"},
{"id" => "WS", "name" => "Samoa"},
{"id" => "SM", "name" => "San Marino"},
{"id" => "ST", "name" => "Sao Tome and Principe"},
{"id" => "SA", "name" => "Saudi Arabia"},
{"id" => "SN", "name" => "Senegal"},
{"id" => "RS", "name" => "Serbia"},
{"id" => "SC", "name" => "Seychelles"},
{"id" => "SL", "name" => "Sierra Leone"},
{"id" => "SG", "name" => "Singapore"},
{"id" => "SX", "name" => "Sint Maarten (Dutch part)"},
{"id" => "SK", "name" => "Slovakia"},
{"id" => "SI", "name" => "Slovenia"},
{"id" => "SB", "name" => "Solomon Islands"},
{"id" => "SO", "name" => "Somalia"},
{"id" => "ZA", "name" => "South Africa"},
{"id" => "GS", "name" => "South Georgia and the South Sandwich Islands"},
{"id" => "SS", "name" => "South Sudan"},
{"id" => "ES", "name" => "Spain"},
{"id" => "LK", "name" => "Sri Lanka"},
{"id" => "SD", "name" => "Sudan"},
{"id" => "SR", "name" => "Suriname"},
{"id" => "SJ", "name" => "Svalbard and Jan Mayen"},
{"id" => "SZ", "name" => "Swaziland"},
{"id" => "SE", "name" => "Sweden"},
{"id" => "CH", "name" => "Switzerland"},
{"id" => "SY", "name" => "Syrian Arab Republic"},
{"id" => "TW", "name" => "Taiwan"},
{"id" => "TJ", "name" => "Tajikistan"},
{"id" => "TZ", "name" => "Tanzania, United Republic of"},
{"id" => "TH", "name" => "Thailand"},
{"id" => "TL", "name" => "Timor-Leste"},
{"id" => "TG", "name" => "Togo"},
{"id" => "TK", "name" => "Tokelau"},
{"id" => "TO", "name" => "Tonga"},
{"id" => "TT", "name" => "Trinidad and Tobago"},
{"id" => "TN", "name" => "Tunisia"},
{"id" => "TR", "name" => "Turkey"},
{"id" => "TM", "name" => "Turkmenistan"},
{"id" => "TC", "name" => "Turks and Caicos Islands"},
{"id" => "TV", "name" => "Tuvalu"},
{"id" => "UG", "name" => "Uganda"},
{"id" => "UA", "name" => "Ukraine"},
{"id" => "AE", "name" => "United Arab Emirates"},
{"id" => "GB", "name" => "United Kingdom"},
{"id" => "US", "name" => "United States"},
{"id" => "UM", "name" => "United States Minor Outlying Islands"},
{"id" => "UY", "name" => "Uruguay"},
{"id" => "UZ", "name" => "Uzbekistan"},
{"id" => "VU", "name" => "Vanuatu"},
{"id" => "VE", "name" => "Venezuela, Bolivarian Republic of"},
{"id" => "VN", "name" => "Viet Nam"},
{"id" => "VG", "name" => "Virgin Islands, British"},
{"id" => "VI", "name" => "Virgin Islands, U.S."},
{"id" => "WF", "name" => "Wallis and Futuna"},
{"id" => "EH", "name" => "Western Sahara"},
{"id" => "YE", "name" => "Yemen"},
{"id" => "ZM", "name" => "Zambia"},
{"id" => "ZW", "name" => "Zimbabwe"},
{"id" => "AX", "name" => "&Aringland Islands"}]

  Country.destroy_all
  countries.each do |country|
    p = Country.new
    p.name = country["name"]
    p.code = country["id"]
    p.save
  end
  puts "There are now #{Country.count} countries registered"
